### PR TITLE
update Dropwizard to 0.8.x

### PR DESCRIPTION
**Pull request by mrserverless**
Updated Dropwizard version to 0.8.0-rc3-SNAPSHOT.
Also made Jetty Servlet, AssertJ and JUnit consistent with current dropwizard versions. 
Removed Guava dependency which is already included as part of Dropwizrad-Core

### CODE REVIEW

**Comment by nbauernfeind** [comment]
This is solid. The project can't be released with a snapshot dependency though.

**Comment by yunspace** [comment]
Thanks, I've reset the DW version to the 0.8.0-rc2 release instead of snapshot.

**Comment by oddcb** [comment]
Hi. Dropwizard 0.8.0 is out. Do you mind updating the PR? Any chance of a release in during the week?

Thanks in advance. :-)

**Comment by yunspace** [comment]
Will update in my morning. Also does anyone object to making the DW dependencies as "provided" scope?

**Comment by nbauernfeind** [comment]
What would be the purpose of making them provided? Maven does a good job using your project's imported version of a project if version conflicts arise.

With DW 0.8.0 being released I will be recreating these repositories in: https://github.com/dropwizard-bundles

I'll get started on this today; thanks for your patience!

**Comment by yunspace** [comment]
Just a thought since most users would already have all the DW dependencies anyway. But yes, maven does a good job of dependency resolution.

I've updated DW version to 0.8.0. Also updated the minor release version to 0.3.0 to correspond with DW's minor version increment.

**Comment by nbauernfeind** [comment]
@yunspace Thanks for your pull request. I've applied these changes (and a few other changes that were released in 0.8.0 in the stock AssetBundle implementation).

I've released a version for dropwizard 0.8.0 and it should be making its way to maven central. Please note that the group id has changed (and that I can no longer close this issue).

```xml
<dependency>
  <groupId>com.nefariouszhen.dropwizard</groupId>
  <artifactId>dropwizard-configurable-assets-bundle</artifactId>
  <version>0.8.0</version>
</dependency>
```

You can see the changes and the repository here:
https://github.com/dropwizard-bundles/dropwizard-configurable-assets-bundle

**Comment by yunspace** [comment]
thanks @nbauernfeind, there are no release tags under https://github.com/dropwizard-bundles/dropwizard-configurable-assets-bundle/releases 

In maven central, the artefact is under `com.nefariouszhen.dropwizard` (as you've noted her), not `io.dropwizard-bundles` as per the README: https://github.com/dropwizard-bundles/dropwizard-configurable-assets-bundle/blob/master/readme.md. This may be a bit confusing for users going off your new repository page.

**Comment by nbauernfeind** [comment]
@yunspace Yes that's correct. I'm going to re-release soon using groupid io.dropwizard-bundles. I'm trying to pull a few strings first. Temporarily you can use the groupId of com.nefariouszhen.dropwizard which is already in maven central.

**Pull request closed without merging**
